---
title: "R Day2"
author: "Tian Fu"
date: "9/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
here::here("data", "gapminder5.csv")

gapminder <- read.csv(here::here("data", "gapminder5.csv"))
head(gapminder)
```

## Converting factors to characters

```{r}
gapminder$country <- as.character(gapminder$country)
gapminder$continent <- as.character(gapminder$continent)
str(gapminder)
```

```{r}
# create a vector of values that we want to repeat the function for
obs <- 1:nrow(gapminder)

for (i in obs) { # the function to repeat is enclosed in braces {}
  gapminder[i, "gdp"] <- gapminder[i, "pop"] * gapminder[i, "gdpPercap"]
}
```

## Creating logged variables with a for loop

```{r}
for (i in obs) {
  gapminder[i, "log_gdpPercap"] <- log(gapminder[i, "gdpPercap"])
  gapminder[i, "log_pop"] <- log(gapminder[i, "pop"])
}
head(gapminder)
gapminder$vec_log_gdpPercap <- log(gapminder$gdpPercap)
all(gapminder$vec_log_gdpPercap == gapminder$log_gdpPercap)
```

```{r}
years <- unique(gapminder$year)

for (i in years) {
  mean_le <- mean(gapminder$lifeExp[gapminder$year == i],
                  na.rm = T)
  print(paste0(i, ":", mean_le))
}
```

```{r}
contin <- unique(gapminder$continent)

for (i in contin) {
  mean_lifeExp <- mean(gapminder$lifeExp[gapminder$continent == i],
                       na.rm = T)
  print(paste0(i, ":", mean_lifeExp))
}
```

```{r}
for (i in contin) {
  print(paste0("Continent: ", i))
  for (j in years) {
    mean_le <- mean(gapminder$lifeExp[gapminder$continent == i &
                                        gapminder$year == j],
                    na.rm = T)
    print(paste0(j, ":", mean_le))
  }
}
```

```{r}
for (i in contin) {
  print(paste0("Continent: ", i))
  for (j in years) {
    sd_le <- sd(gapminder$lifeExp[gapminder$continent == i &
                                    gapminder$year == j],
                na.rm = T)
    print(paste0(j, ":", sd_le))
  }
}
```

```{r}
vars <- gapminder[, c("lifeExp", "pop", "gdpPercap")]
apply(vars, 2, mean)
```

```{r}
print(names(vars))
lapply(gapminder, mean)
```

```{r}
sapply(years, function(x) mean(gapminder$lifeExp[gapminder$year == x]))
```

## while loop

```{r}
i <- 1952 # define the iterator
while (i < 1987) {
  sd_le <- sd(gapminder$lifeExp[gapminder$year == i])
  print(paste0(i, ":", sd_le))
  i <- i + 5 # increase the iterator by the interval between years
}
```

```{r}
i <- 1987
while (i <= 2002) {
  sd_le <- sd(gapminder$lifeExp[gapminder$year == i])
  print(paste0(i, ":", sd_le))
  i <- i + 5
}
```

```{r}
set.seed(1)
random_year = sample(gapminder$year, 1)
random_year

if (random_year > 1977) {
  print(random_year)
}
```

```{r}
for (i in unique(gapminder$year)) {
  if (i >= 1987) {
    mean_pop <- mean(gapminder$pop[gapminder$year == i])
    print(paste0("mean pop in ", i, " is: ", mean_pop))
  } else {
    print(paste0(i, " is smaller than 1987"))
  }
}
```
```{r}
report_mean_sd <-
  function(df, variable, country) {
    var <- df[[variable]][df$country == country]
    m_le <- mean(var)
    sd_le <- sd(var)
    cat("Country:", country,
        "\nMean Life Expectancy:", m_le,
        "\nSD Life Expectancy:", sd_le)
  }
report_mean_sd(gapminder, "lifeExp", "Bulgaria")
```

```{r}
report_sum <-
  function(df, variable, continent){
    var <- df[[variable]][df$continent == continent]
    maximum <- max(var)
    minimum <- min(var)
    mean <- mean(var)
    median <- median(var)
    cat("Continent:", continent,
        "\nMean Life Expectancy:", mean,
        "\nMedian Life Expectancy:", median,
        "\nMax Life Expectancy:", maximum,
        "\nMin Life Expectancy:", minimum)
  }
report_sum(gapminder, "lifeExp", "Asia")
```




## exercises

```{r}
if (any(gapminder$year == 2002)) {
  print(paste0("there is 2002"))
} else {
  print(paste0("there is no 2002"))
}
if (any(gapminder$year == 2012)) {
  print(paste0("there is 2012"))
} else {
  print(paste0("there is no 2012"))
}
```

```{r}
whole_mean <- mean(gapminder$pop)
for (i in unique(gapminder$country)) {
  indiv_mean = mean(gapminder$pop[gapminder$country == i])
  if (indiv_mean < whole_mean) {
    mean_le <- mean(gapminder$lifeExp[gapminder$country == i])
    cat(paste0("\nMean life expectancy in ", i, " is ", mean_le))
  }
}
```

```{r}
for (i in unique(gapminder$continent)) {
  mean_le <- mean(gapminder$lifeExp[gapminder$continent == i])
  if (mean_le < 50) {
    print(paste("Mean life expectancy in", i, "< 50"))
  }
  if (mean_le > 70) {
    print(paste("Mean life expectancy in", i, "> 70"))
  }
  if ((mean_le > 50) & (mean_le < 70)) {
    print(paste("Mean life expectancy in", i, "is between 50 and 70"))
  }
}
```

```{r}
report_name_class <-
  function(df) {
    for (i in names(df)) {
      class <- class(df[[i]])
      print(paste("column name:", i, ";",
                "class type:", class))
    }
  }
report_name_class(gapminder)
```

```{r}
report_name_class <-
  function(df) {
    names <- names(df)
    for (i in 1:ncol(df)) {
      name <- names[i]
      class <- class(df[[name]])
      print(paste("column name:", name, ";",
                "class type:", class))
    }
  }
report_name_class(gapminder)
```

```{r}
report_mean_std <-
  function(vector, med = FALSE) {
    mean = mean(vector)
    sd = sd(vector)
    print(paste("mean is", mean, 
                "standard deviation is", sd))
    if (med) {
      median = median(vector)
      print(paste("median is", median))
    }
  }
report_mean_std(c(4,5,6), TRUE)
```

```{r}
gapminder$log_lifeExp <- log(gapminder$lifeExp)
plot(gapminder$log_lifeExp ~ gapminder$log_gdpPercap,
     main="log of gdp per capita and log of life expectancy",
     xlab = "gdp per capita", ylab = "life expectancy")

for (i in unique(gapminder$year)) {
  plot(gapminder$log_lifeExp[gapminder$year==i] ~ gapminder$log_gdpPercap[gapminder$year==i],
     main=i,
     xlab = "gdp per capita", ylab = "life expectancy")
}
```

```{r}
for (i in unique(gapminder$continent)) {
  if (i == "Americas") {
    plot(gapminder$log_lifeExp[gapminder$country=="Canada"] ~ gapminder$log_gdpPercap[gapminder$country=="Canada"],
     main="North America",
     xlab = "gdp per capita", ylab = "life expectancy")
    plot(gapminder$log_lifeExp[gapminder$continent==i &
                                   gapminder$country!="Canada"] ~ gapminder$log_gdpPercap[gapminder$continent==i &                                                                    gapminder$country!="Canada"],
     main="South America",
     xlab = "gdp per capita", ylab = "life expectancy")
  } else {
    plot(gapminder$log_lifeExp[gapminder$continent==i] ~ gapminder$log_gdpPercap[gapminder$continent==i],
         main=i,
         xlab = "gdp per capita", ylab = "life expectancy")
  }
}

plot(gapminder$log_lifeExp[gapminder$continent=="Americas"] ~ gapminder$log_gdpPercap[gapminder$continent=="Americas"],
         main="Americas",
         xlab = "gdp per capita", ylab = "life expectancy")
```

